name: Terraform CI workflow

on:
  push:
    branches:
      - fix-workflow
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types: [published]


jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false
          
      - name: Terraform format check
        id: fmt
        run: terraform fmt -check
        
      - name: Terraform init
        id: init
        run: terraform init
        
      - name: Terraform validation
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -var db_pass=${{ secrets.DB_PASS }} -no-color

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo "environment=live" >> $GITHUB_OUTPUT          
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then echo "environment=stage" >> $GITHUB_OUTPUT
          else echo "environment=unknown" >> $GITHUB_OUTPUT
          fi
          
      - name: Terraform print env
        run: |
          echo "${{steps.check-tag.outputs.environment}}"

      - name: Terraform test 1
        if: github.event_name == 'push' || github.event_name == 'release'
        run: |
          echo "Terraform test 1: ${{ steps.check-tag.outputs.environment }}"

      - name: Terraform test 2
        if: steps.check-tag.outputs.environment == 'stage' && github.event_name == 'push'
        run: |
          echo "Terraform test 2: ${{ steps.check-tag.outputs.environment }}"

      - name: Terraform test 3
        if: steps.check-tag.outputs.environment == 'live' && github.event_name == 'release'
        run: |
          echo "Terraform test 3: ${{ steps.check-tag.outputs.environment }}"
